export const realQuestionsMap: Record<string, any[]> = {
  'Module 1: HTML basics': [
    { question: 'What does HTML stand for?', points: 10, options: [{text: 'Hyper Text Markup Language', isCorrect: true}, {text: 'Hot Mail', isCorrect: false}, {text: 'How to Make Lasagna', isCorrect: false}, {text: 'Hyperlinks Text Mark Language', isCorrect: false}] },
    { question: 'Who is making the Web standards?', points: 10, options: [{text: 'Google', isCorrect: false}, {text: 'Mozilla', isCorrect: false}, {text: 'Microsoft', isCorrect: false}, {text: 'The World Wide Web Consortium', isCorrect: true}] },
    { question: 'Choose the correct HTML element for the largest heading:', points: 10, options: [{text: '<heading>', isCorrect: false}, {text: '<h6>', isCorrect: false}, {text: '<h1>', isCorrect: true}, {text: '<head>', isCorrect: false}] },
    { question: 'What is the correct HTML element for inserting a line break?', points: 10, options: [{text: '<break>', isCorrect: false}, {text: '<lb>', isCorrect: false}, {text: '<br>', isCorrect: true}, {text: '<brk>', isCorrect: false}] },
    { question: 'What is the correct HTML for adding a background color?', points: 10, options: [{text: '<body style="background-color:yellow;">', isCorrect: true}, {text: '<background>yellow</background>', isCorrect: false}, {text: '<body bg="yellow">', isCorrect: false}, {text: '<body color="yellow">', isCorrect: false}] },
    { question: 'Choose the correct HTML element to define important text', points: 10, options: [{text: '<b>', isCorrect: false}, {text: '<strong>', isCorrect: true}, {text: '<important>', isCorrect: false}, {text: '<i>', isCorrect: false}] },
    { question: 'Choose the correct HTML element to define emphasized text', points: 10, options: [{text: '<em>', isCorrect: true}, {text: '<italic>', isCorrect: false}, {text: '<i>', isCorrect: false}, {text: '<strong>', isCorrect: false}] },
    { question: 'What is the correct HTML for creating a hyperlink?', points: 10, options: [{text: '<a>http://www.w3schools.com</a>', isCorrect: false}, {text: '<a href="http://www.w3schools.com">W3Schools</a>', isCorrect: true}, {text: '<a url="http://www.w3schools.com">W3Schools.com</a>', isCorrect: false}, {text: '<a name="http://www.w3schools.com">W3Schools.com</a>', isCorrect: false}] },
    { question: 'Which character is used to indicate an end tag?', points: 10, options: [{text: '*', isCorrect: false}, {text: '/', isCorrect: true}, {text: '^', isCorrect: false}, {text: '<', isCorrect: false}] },
    { question: 'How can you open a link in a new tab/browser window?', points: 10, options: [{text: '<a href="url" new>', isCorrect: false}, {text: '<a href="url" target="new">', isCorrect: false}, {text: '<a href="url" target="_blank">', isCorrect: true}, {text: '<a href="url" target="_blank_window">', isCorrect: false}] }
  ],
  'Module 2: CSS advanced': [
    { question: 'What does CSS stand for?', points: 10, options: [{text: 'Cascading Style Sheets', isCorrect: true}, {text: 'Colorful Style Sheets', isCorrect: false}, {text: 'Creative Style Sheets', isCorrect: false}, {text: 'Computer Style Sheets', isCorrect: false}] },
    { question: 'What is the correct HTML for referring to an external style sheet?', points: 10, options: [{text: '<style src="mystyle.css">', isCorrect: false}, {text: '<link rel="stylesheet" type="text/css" href="mystyle.css">', isCorrect: true}, {text: '<stylesheet>mystyle.css</stylesheet>', isCorrect: false}, {text: '<link url="mystyle.css">', isCorrect: false}] },
    { question: 'Where in an HTML document is the correct place to refer to an external style sheet?', points: 10, options: [{text: 'In the <body> section', isCorrect: false}, {text: 'In the <head> section', isCorrect: true}, {text: 'At the end of the document', isCorrect: false}, {text: 'You can\'t link to external css', isCorrect: false}] },
    { question: 'Which HTML tag is used to define an internal style sheet?', points: 10, options: [{text: '<style>', isCorrect: true}, {text: '<script>', isCorrect: false}, {text: '<css>', isCorrect: false}, {text: '<link>', isCorrect: false}] },
    { question: 'Which HTML attribute is used to define inline styles?', points: 10, options: [{text: 'class', isCorrect: false}, {text: 'style', isCorrect: true}, {text: 'font', isCorrect: false}, {text: 'styles', isCorrect: false}] },
    { question: 'Which is the correct CSS syntax?', points: 10, options: [{text: 'body {color: black;}', isCorrect: true}, {text: '{body;color:black;}', isCorrect: false}, {text: '{body:color=black;}', isCorrect: false}, {text: 'body:color=black;', isCorrect: false}] },
    { question: 'How do you insert a comment in a CSS file?', points: 10, options: [{text: '\' this is a comment', isCorrect: false}, {text: '/* this is a comment */', isCorrect: true}, {text: '// this is a comment //', isCorrect: false}, {text: '<!-- this is a comment -->', isCorrect: false}] },
    { question: 'Which property is used to change the background color?', points: 10, options: [{text: 'color', isCorrect: false}, {text: 'bgcolor', isCorrect: false}, {text: 'background-color', isCorrect: true}, {text: 'bg', isCorrect: false}] },
    { question: 'How do you add a background color for all <h1> elements?', points: 10, options: [{text: 'all.h1 {background-color:#FFFFFF;}', isCorrect: false}, {text: 'h1.all {background-color:#FFFFFF;}', isCorrect: false}, {text: 'h1 {background-color:#FFFFFF;}', isCorrect: true}, {text: 'h1 {bgcolor:#FFFFFF;}', isCorrect: false}] },
    { question: 'Which CSS property creates a Flexbox layout?', points: 10, options: [{text: 'display: block', isCorrect: false}, {text: 'display: flex', isCorrect: true}, {text: 'float: left', isCorrect: false}, {text: 'position: flex', isCorrect: false}] }
  ],
  'Module 3: JavaScript Deep Dive': [
    { question: 'Inside which HTML element do we put the JavaScript?', points: 10, options: [{text: '<scripting>', isCorrect: false}, {text: '<javascript>', isCorrect: false}, {text: '<script>', isCorrect: true}, {text: '<js>', isCorrect: false}] },
    { question: 'Where is the correct place to insert a JavaScript?', points: 10, options: [{text: 'The <head> section', isCorrect: false}, {text: 'The <body> section', isCorrect: false}, {text: 'Both the <head> section and the <body> section are correct', isCorrect: true}, {text: 'Inside the <footer> only', isCorrect: false}] },
    { question: 'What is the correct syntax for referring to an external script called "xxx.js"?', points: 10, options: [{text: '<script name="xxx.js">', isCorrect: false}, {text: '<script href="xxx.js">', isCorrect: false}, {text: '<script src="xxx.js">', isCorrect: true}, {text: '<script url="xxx.js">', isCorrect: false}] },
    { question: 'How do you write "Hello World" in an alert box?', points: 10, options: [{text: 'msg("Hello World");', isCorrect: false}, {text: 'alertBox("Hello World");', isCorrect: false}, {text: 'alert("Hello World");', isCorrect: true}, {text: 'msgBox("Hello World");', isCorrect: false}] },
    { question: 'How do you create a function in JavaScript?', points: 10, options: [{text: 'function myFunction()', isCorrect: true}, {text: 'function = myFunction()', isCorrect: false}, {text: 'function:myFunction()', isCorrect: false}, {text: 'create myFunction()', isCorrect: false}] },
    { question: 'How do you call a function named "myFunction"?', points: 10, options: [{text: 'call function myFunction()', isCorrect: false}, {text: 'call myFunction()', isCorrect: false}, {text: 'myFunction()', isCorrect: true}, {text: 'execute myFunction()', isCorrect: false}] },
    { question: 'How to write an IF statement in JavaScript?', points: 10, options: [{text: 'if i = 5 then', isCorrect: false}, {text: 'if i == 5 then', isCorrect: false}, {text: 'if (i == 5)', isCorrect: true}, {text: 'if i = 5', isCorrect: false}] },
    { question: 'How does a WHILE loop start?', points: 10, options: [{text: 'while (i <= 10; i++)', isCorrect: false}, {text: 'while (i <= 10)', isCorrect: true}, {text: 'while i = 1 to 10', isCorrect: false}, {text: 'while (i <= 10;)', isCorrect: false}] },
    { question: 'How can you add a comment in a JavaScript?', points: 10, options: [{text: '<!--This is a comment-->', isCorrect: false}, {text: '//This is a comment', isCorrect: true}, {text: '\'This is a comment', isCorrect: false}, {text: '**This is a comment**', isCorrect: false}] },
    { question: 'What is the correct way to write a JavaScript array?', points: 10, options: [{text: 'var colors = (1:"red", 2:"green", 3:"blue")', isCorrect: false}, {text: 'var colors = ["red", "green", "blue"]', isCorrect: true}, {text: 'var colors = "red", "green", "blue"', isCorrect: false}, {text: 'var colors = 1 = ("red"), 2 = ("green"), 3 = ("blue")', isCorrect: false}] }
  ],
  'Module 4: React Framework': [
    { question: 'What is React?', points: 10, options: [{text: 'A JavaScript library for building user interfaces', isCorrect: true}, {text: 'A CSS framework', isCorrect: false}, {text: 'A database management system', isCorrect: false}, {text: 'A server-side language', isCorrect: false}] },
    { question: 'Who developed React?', points: 10, options: [{text: 'Google', isCorrect: false}, {text: 'Facebook', isCorrect: true}, {text: 'Microsoft', isCorrect: false}, {text: 'Twitter', isCorrect: false}] },
    { question: 'What is JSX?', points: 10, options: [{text: 'A syntax extension to JavaScript', isCorrect: true}, {text: 'A new programming language', isCorrect: false}, {text: 'A type of JSON database', isCorrect: false}, {text: 'A styling framework', isCorrect: false}] },
    { question: 'What hook is used to manage state in a React functional component?', points: 10, options: [{text: 'useEffect', isCorrect: false}, {text: 'useState', isCorrect: true}, {text: 'useContext', isCorrect: false}, {text: 'useReducer', isCorrect: false}] },
    { question: 'What hook is used to perform side effects in a function component?', points: 10, options: [{text: 'useState', isCorrect: false}, {text: 'useContext', isCorrect: false}, {text: 'useEffect', isCorrect: true}, {text: 'useSideEffect', isCorrect: false}] },
    { question: 'What is the purpose of the virtual DOM in React?', points: 10, options: [{text: 'To improve SEO', isCorrect: false}, {text: 'To make the app run off-line', isCorrect: false}, {text: 'To optimize rendering performance', isCorrect: true}, {text: 'To replace the actual DOM entirely', isCorrect: false}] },
    { question: 'How do you pass data from a parent component to a child component?', points: 10, options: [{text: 'Using state', isCorrect: false}, {text: 'Using Context API only', isCorrect: false}, {text: 'Using props', isCorrect: true}, {text: 'Using Redux', isCorrect: false}] },
    { question: 'Which of the following is true about props in React?', points: 10, options: [{text: 'Props are mutable', isCorrect: false}, {text: 'Props are read-only', isCorrect: true}, {text: 'Props can only be strings', isCorrect: false}, {text: 'Props are exactly the same as state', isCorrect: false}] },
    { question: 'What does "lifting state up" mean in React?', points: 10, options: [{text: 'Moving state to a lower-level component', isCorrect: false}, {text: 'Moving state to an external store', isCorrect: false}, {text: 'Moving state to a common ancestor component to share it', isCorrect: true}, {text: 'Uploading state to the server', isCorrect: false}] },
    { question: 'What is the default port for a React app created with create-react-app?', points: 10, options: [{text: '8080', isCorrect: false}, {text: '3000', isCorrect: true}, {text: '5000', isCorrect: false}, {text: '4000', isCorrect: false}] }
  ],
  'Module 5: Node Backend': [
    { question: 'What is Node.js?', points: 10, options: [{text: 'A frontend framework', isCorrect: false}, {text: 'A JavaScript runtime built on Chrome\'s V8 engine', isCorrect: true}, {text: 'A relational database', isCorrect: false}, {text: 'A python library', isCorrect: false}] },
    { question: 'Which module in Node.js is used to create a web server?', points: 10, options: [{text: 'http', isCorrect: true}, {text: 'fs', isCorrect: false}, {text: 'url', isCorrect: false}, {text: 'path', isCorrect: false}] },
    { question: 'What does npm stand for?', points: 10, options: [{text: 'Node Package Manager', isCorrect: true}, {text: 'New Project Manager', isCorrect: false}, {text: 'Node Programming Module', isCorrect: false}, {text: 'Network Protocol Manager', isCorrect: false}] },
    { question: 'Which Node.js framework is most commonly used to build web applications?', points: 10, options: [{text: 'Django', isCorrect: false}, {text: 'Express.js', isCorrect: true}, {text: 'Laravel', isCorrect: false}, {text: 'Spring Boot', isCorrect: false}] },
    { question: 'How do you import a module in Node.js using CommonJS?', points: 10, options: [{text: 'import module from "module"', isCorrect: false}, {text: 'include "module"', isCorrect: false}, {text: 'require("module")', isCorrect: true}, {text: 'use "module"', isCorrect: false}] },
    { question: 'What is the purpose of the package.json file?', points: 10, options: [{text: 'To store database queries', isCorrect: false}, {text: 'To manage project dependencies and scripts', isCorrect: true}, {text: 'To configure the operating system', isCorrect: false}, {text: 'To write CSS styles', isCorrect: false}] },
    { question: 'Which method is used to read a file asynchronously in Node.js?', points: 10, options: [{text: 'fs.readFileSync()', isCorrect: false}, {text: 'fs.readFile()', isCorrect: true}, {text: 'fs.read()', isCorrect: false}, {text: 'fs.readAsync()', isCorrect: false}] },
    { question: 'What is a callback in Node.js?', points: 10, options: [{text: 'A function passed as an argument to another function', isCorrect: true}, {text: 'A variable scope', isCorrect: false}, {text: 'A database query', isCorrect: false}, {text: 'A way to style applications', isCorrect: false}] },
    { question: 'Which of the following describes the Node.js event loop?', points: 10, options: [{text: 'It makes Node.js multi-threaded', isCorrect: false}, {text: 'It handles asynchronous operations in a single thread', isCorrect: true}, {text: 'It pauses all code until execution is complete', isCorrect: false}, {text: 'It only runs when an error occurs', isCorrect: false}] },
    { question: 'How can you install an npm package globally?', points: 10, options: [{text: 'npm install --global <package>', isCorrect: true}, {text: 'npm install --save <package>', isCorrect: false}, {text: 'npm global install <package>', isCorrect: false}, {text: 'npm add -g <package>', isCorrect: false}] }
  ]
};
